### ISSUE TITLE
variables to be changed

### ISSUE THREAD

**Issue by corsaro1** [dan-da/zcash-util#1]
to adapt this script to latest zcash testnet versions, change these two variables:

encryptedbucket1 to encryptednote1
zcrawpour to zcrawjoinsplit

**Comment by dan-da** [comment]
thanks.  any chance you can submit a pull request?   I don't presently have latest zcash code to test with.

**Comment by corsaro1** [comment]
ok, pull request made

**Comment by dan-da** [comment]
merged, closing.
